name: fastguard
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  division: ^0.8.7+2
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.3+1
  flutter_bloc: ^3.1.0
  google_sign_in: ^4.0.0
  firebase_auth: ^0.15.0+1
  equatable: ^1.0.0
  meta: ^1.1.6
  font_awesome_flutter: ^8.4.0
  flutter_launcher_icons: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
 
flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon.png"